-- MySQL Script generated by MySQL Workbench
-- Mon Oct  3 09:29:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema c3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema c3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `c3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `c3` ;

-- -----------------------------------------------------
-- Table `c3`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c3`.`accounts` (
  `username` VARCHAR(255) NOT NULL,
  `password` LONGTEXT NULL DEFAULT NULL,
  `email` LONGTEXT NULL DEFAULT NULL,
  `status` TINYINT NULL DEFAULT '1',
  `belongsTo` LONGTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `c3`.`application`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c3`.`application` (
  `app_acronym` VARCHAR(255) NOT NULL,
  `app_description` LONGTEXT NULL DEFAULT NULL,
  `app_rnumber` INT NULL DEFAULT NULL,
  `app_startDate` DATE NULL DEFAULT NULL,
  `app_endDate` DATE NULL DEFAULT NULL,
  `app_permit_create` VARCHAR(255) NULL DEFAULT NULL,
  `app_permit_open` VARCHAR(255) NULL DEFAULT NULL,
  `app_permit_toDoList` VARCHAR(255) NULL DEFAULT NULL,
  `app_permit_doing` VARCHAR(255) NULL DEFAULT NULL,
  `app_permit_done` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`app_acronym`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `c3`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c3`.`plan` (
  `plan_mvp_name` VARCHAR(255) NOT NULL,
  `plan_startDate` DATE NULL DEFAULT NULL,
  `plan_endDate` DATE NULL DEFAULT NULL,
  `plan_app_acronym` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`plan_mvp_name`, `plan_app_acronym`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `c3`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c3`.`task` (
  `task_name` VARCHAR(255) NULL DEFAULT NULL,
  `task_description` LONGTEXT NULL DEFAULT NULL,
  `task_notes` VARCHAR(255) NULL DEFAULT NULL,
  `task_id` VARCHAR(500) NOT NULL,
  `task_plan` VARCHAR(255) NULL DEFAULT NULL,
  `task_app_acronym` VARCHAR(255) NULL DEFAULT NULL,
  `task_state` VARCHAR(255) NULL DEFAULT NULL,
  `task_creator` VARCHAR(255) NULL DEFAULT NULL,
  `task_owner` VARCHAR(255) NULL DEFAULT NULL,
  `task_createDate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`task_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `c3`.`usergroup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `c3`.`usergroup` (
  `groupname` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`groupname`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
